# -*- coding: utf-8 -*-
lang_dict_deepl = {
    "None": "None",
    "Bulgarian|Български език": "BG",
    "Czech|Čeština": "CS",
    "Danish|Dansk": "DA",
    "German|Deutsch": "DE",
    "Greek|Ελληνικά": "EL",
    "English (British)": "EN|GB",
    "English (American)": "EN|US",
    "Spanish|Español": "ES",
    "Estonian|Eesti keel": "ET",
    "Finnish|Suomi": "FI",
    "French|Français": "FR",
    "Hungarian|Magyar": "HU",
    "Italian|Italiano": "IT",
    "Japanese|日本語": "JA",
    "Lithuanian|Lietuvių kalba": "LT",
    "Latvian|Latviešu valoda": "LV",
    "Dutch|Nederlands": "NL",
    "Norwegian (Bokmål)|Norsk (Bokmål)": "NB",
    "Polish|Polski": "PL",
    "Portuguese|Português": "PT|PT",
    "Portuguese (Brazilian)|Português (Brasileiro)": "PT|BR",
    "Romanian|Română": "RO",
    "Russian|Русский": "RU",
    "Slovak|Slovenčina": "SK",
    "Slovenian|Slovenščina": "SL",
    "Swedish|Svenska": "SV",
    "Chinese (Simplified)|简体中文": "ZH",
}

lang_dict_google = {
    "None": "None",
    "Afrikaans": "af",
    "Albanian|Gjuha shqipe": "sq",
    "Amharic|አማርኛ": "am",
    "Arabic|اَلْعَرَبِيَّةُ": "ar",
    "Armenian|Հայերեն": "hy",
    "Assamese|অসমীয়া": "as",
    "Aymara|Aymar aru": "ay",
    "Azerbaijani|Azərbaycan dili": "az",
    "Bambara|Bamanankan": "bm",
    "Basque|Euskara": "eu",
    "Belarusian|Беларуская мова": "be",
    "Bengali|বাংলা": "bn",
    "Bhojpuri|भोजपुरी": "bho",
    "Bosnian|Bosanski jezik": "bs",
    "Bulgarian|Български език": "bg",
    "Catalan|Català": "ca",
    "Cebuano|Sinugboanong Binisaya": "ceb",
    "Chinese (Simplified)|简体中文": "zh-CN",
    "Chinese (Traditional)|繁體中文": "zh-TW",
    "Corsican|Corsu": "co",
    "Croatian|Hrvatski": "hr",
    "Czech|Čeština": "cs",
    "Danish|Dansk": "da",
    "Dhivehi|ދިވެހި": "dv",
    "Dutch|Nederlands": "nl",
    "English": "en",
    "Esperanto": "eo",
    "Estonian|Eesti keel": "et",
    "Ewe|Eʋegbe": "ee",
    "Filipino (Tagalog)|Wikang Tagalog": "fil",
    "Finnish|Suomi": "fi",
    "French|Français": "fr",
    "Frisian|Frysk": "fy",
    "Galician|Galego": "gl",
    "Georgian|ქართული": "ka",
    "German|Deutsch": "de",
    "Greek|Ελληνικά": "el",
    "Guarani|Avañe'ẽ": "gn",
    "Gujarati|ગુજરાતી": "gu",
    "Haitian Creole|Kreyòl ayisyen": "ht",
    "Hausa|هَوُسَ": "ha",
    "Hawaiian|ʻŌlelo Hawaiʻi": "haw",
    "Hebrew|עברית": "he",
    "Hindi|हिन्दी": "hi",
    "Hmong|Hmoob": "hmn",
    "Hungarian|Magyar": "hu",
    "Icelandic|Íslenska": "is",
    "Igbo|Asụsụ Igbo": "ig",
    "Indonesian|Bahasa Indonesia": "id",
    "Irish|Gaeilge": "ga",
    "Italian|Italiano": "it",
    "Japanese|日本語": "ja",
    "Javanese|ꦧꦱꦗꦮ": "jv",
    "Kannada|ಕನ್ನಡ": "kn",
    "Kazakh|Қазақ тілі": "kk",
    "Khmer|ភាសាខ្មែរ": "km",
    "Kinyarwanda|Ikinyarwanda": "rw",
    "Konkani|कोंकणी": "gom",
    "Korean|한국어": "ko",
    "Krio|Krio": "kri",
    "Kurdish|Kurdî": "ku",
    "Kurdish (Sorani)|کوردیی ناوەندی": "ckb",
    "Kyrgyz|Кыргызча": "ky",
    "Lao|ພາສາລາວ": "lo",
    "Latin|Latine": "la",
    "Latvian|Latviešu valoda": "lv",
    "Lingala|Lingála": "ln",
    "Lithuanian|Lietuvių kalba": "lt",
    "Luganda|Oluganda": "lg",
    "Luxembourgish|Lëtzebuergesch": "lb",
    "Macedonian|Македонски јазик": "mk",
    "Maithili|मैथिली, মৈথিলী": "mai",
    "Malagasy|Malagasy fiteny": "mg",
    "Malay|Bahasa Melayu": "ms",
    "Malayalam|മലയാളം": "ml",
    "Maltese|Malti": "mt",
    "Maori|Te reo Māori": "mi",
    "Marathi|मराठी": "mr",
    "Meiteilon (Manipuri)|ꯃꯩꯇꯩꯂꯣꯟ": "mni-Mtei",
    "Mizo|lus": "lus",
    "Mongolian|Монгол хэл": "mn",
    "Myanmar (Burmese)|ဗမာစာ": "my",
    "Nepali|नेपाली": "ne",
    "Norwegian|Norsk": "no",
    "Nyanja (Chichewa)|ChiCheŵa, chinyanja": "ny",
    "Odia (Oriya)|ଓଡ଼ିଆ": "or",
    "Oromo|Afaan Oromoo": "om",
    "Pashto|پښتو": "ps",
    "Persian|فارسی": "fa",
    "Polish|Polski": "pl",
    "Portuguese (Portugal, Brazil)|Portuguê": "pt",
    "Punjabi|ਪੰਜਾਬੀ": "pa",
    "Quechua|Runa Simi": "qu",
    "Romanian|Română": "ro",
    "Russian|Русский": "ru",
    "Samoan|Gagana fa'a Samoa": "sm",
    "sanskrit|संस्कृतम्": "sa",
    "Scots Gaelic|Gàidhlig": "gd",
    "Sepedi|Sesotho": "nso",
    "Serbian|Српски језик": "sr",
    "Sesotho|Sesotho": "st",
    "Shona|ChiShona": "sn",
    "Sindhi|سنڌي، سندھی ، सिन्ध": "sd",
    "Sinhala (Sinhalese)|සිංහල": "si",
    "Slovak|Slovenčina": "sk",
    "Slovenian|Slovenščina": "sl",
    "Somali|Soomaaliga, af Soomaali": "so",
    "Spanish|Español": "es",
    "Sundanese|Basa Sunda": "su",
    "Swahili|Kiswahili": "sw",
    "Swedish|Svenska": "sv",
    "Tagalog (Filipino)|Wikang Tagalog": "tl",
    "Tajik|Форсии Тоҷикӣ": "tg",
    "Tamil|தமிழ்": "ta",
    "Tatar|татар теле, tatar tele": "tt",
    "Telugu|తెలుగు": "te",
    "Thai|ภาษาไทย": "th",
    "Tigrinya|ትግርኛ": "ti",
    "Tonga|Faka Tonga": "to",
    "Turkish|Türkçe": "tr",
    "Turkmen|Türkmen, Түркмен": "tk",
    "Twi (Akan)": "ak",
    "Ukrainian|Українська": "uk",
    "Urdu|اردو": "ur",
    "Uyghur|ئۇيغۇر تىلى": "ug",
    "Uzbek|اۉزبېکچه, اۉزبېک تیلی": "uz",
    "Vietnamese|Tiếng Việt": "vi",
    "Welsh|Cymraeg": "cy",
    "Xhosa|isiXhosa": "xh",
    "Yiddish|ייִדיש": "yi",
    "Yoruba|Yorùbá": "yo",
    "Zulu|isiZulu": "zu",
}
